export const LanguageExtensions = {
    javascript: ".js",
    typescript: ".ts",
    python: ".py",
    java: ".java",
    csharp: ".cs",
    php: ".php",
    ruby: ".rb",
    go: ".go",
    rust: ".rs",
    kotlin: ".kt",
    swift: ".swift",
    dart: ".dart",
    scala: ".scala",
    clojure: ".clj",
    haskell: ".hs",
    perl: ".pl",
    lua: ".lua",
    sql: ".sql",
    bash: ".sh",
    assembly: ".asm",
    fortran: ".f90",
    vbnet: ".vb",
    ocaml: ".ml",
    prolog: ".pl",
};
  